version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartfrete-app
    working_dir: /var/www/smartfrete
    volumes:
      - ./smartfrete:/var/www/smartfrete
    depends_on:
      - db
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - smartfrete-net

  db:
    image: postgres:15
    container_name: smartfrete-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - smartfrete-net

  nginx:
    image: nginx:latest
    container_name: smartfrete-nginx
    ports:
      - "80:80"
    volumes:
      - ./smartfrete:/var/www/smartfrete
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - smartfrete-net

volumes:
  pgdata:

networks:
  smartfrete-net:
    driver: bridge